### ISSUE TITLE
README: Add basic content

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/intouch-ios#1]
App title, description, how to clone and build, copyright.

**Comment by gonzalky7** [comment]
@ybakos  please review readme.md if I missed anything

**Comment by ybakos** [comment]
@gonzalky7 This is AWESOME! Nice work. Some suggestions:

Main header:

# Abilitree Intouch Mobile

And at the very bottom:

(c) 2017 Kyleen Gonzalez, Aaron Baker and Abilitree
