### ISSUE TITLE
Missing .gitignore

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/intouch-ios#2]
I believe you should delete everything, create a proper .gitignore, and then create the project again.

**Comment by gonzalky7** [comment]
Recreated the project and add the .gitignore

**Comment by ybakos** [comment]
@gonzalky7 Almost. Be sure to dig into what should be in the .gitignore.
See https://github.com/github/gitignore/blob/master/Global/Xcode.gitignore

In other words, with this latest project there are still things that are in the repo that should not be:

![screen shot 2017-11-04 at 11 28 23 am](https://user-images.githubusercontent.com/5502/32408342-7765762c-c153-11e7-839d-ee952fd1510b.png)

Let's do this one more time (this is ok!). Delete everything (make a backup copy of the readme - it's great). Edit the .gitignore, then recreate the xcode project.

BTW, when configuring the project, use the following attributes:
![screen shot 2017-11-04 at 11 32 41 am](https://user-images.githubusercontent.com/5502/32408372-e9cf1e34-c153-11e7-95a9-c4a9853a23c3.png)

You've got this!

**Comment by gonzalky7** [comment]
!!!!!! ok third times a charm I do not see that file anymore.

**Comment by ybakos** [comment]
🎉 🎉 🎉 🎉  You got it. Excellent.

The "best practice" here is, whenever starting a project, create a little README and a .gitignore that is appropriate for the project.
