### ISSUE TITLE
pod install error: Could not automatically select and Xcode project

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/intouch-ios#9]
When following the README, and executing `pod install --repo-update`, the following error is raised:

```
Analyzing dependencies
[!] Could not automatically select an Xcode project. Specify one in your Podfile like so:

    project 'path/to/Project.xcodeproj'
```

**Comment by Aaronmb123** [comment]
@ybakos I updated master. Pull and try pod install again.

**Comment by ybakos** [comment]
@Aaronmb123 Notice the error notice that I posted. It's asking you to add a `project` declaration in the _Podfile_. (I don't see this in the _Podfile_.)

**Comment by ybakos** [comment]
@Aaronmb123 The addition in this commit: 7b061454738718649e74d1c66f2b21330c8cd2bf is still not right - see the error message at the top of this issue. `project 'intouch'` isn't right.

**Comment by ybakos** [comment]
![screen shot 2018-05-09 at 10 52 37 pm](https://user-images.githubusercontent.com/5502/39854240-b5d5f8a8-53db-11e8-8ce9-4e6b826dc6f3.png)

**Comment by ybakos** [comment]
@Aaronmb123 My local repo was not in sync with the remote, and still had the original InTouch Mobile.xcodeproj. This issue is resolved.
